
import { Service, Technology, TeamMember, Testimonial, Location, ServiceCategory } from './types';
import anaCorderoImage from './Doctores/Ana Cordero.jpeg';
import winiferDominguezImage from './Doctores/DraWiniferDomínguez.jpeg';
import manuelaPichardoImage from './Doctores/Dra. Manuela Pichardo.jpg';

export const SERVICES_DATA: Service[] = [
    // Armonización Facial
    { id: 1, name: 'Aumento de Labios', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/7qxYfcHj/Aumento-de-labios-2.png', description: 'Nuestro tratamiento de aumento de labios con ácido hialurúnico está diseñado para realzar tu belleza natural, proporcionando volumen y definición a tus labios de manera segura y efectiva.' },
    { id: 2, name: 'Relleno de Ojeras', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/5bmfd35J/Relleno-de-ojeras.png', description: 'Nuestro tratamiento de relleno de ojeras está diseñado para rejuvenecer tu mirada, eliminando el aspecto cansado y fatigado que puede ser causado por ojeras marcadas.' },
    { id: 3, name: 'Reposicionamiento Malar', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/nncpHDTm/Reposicionamiento-malar.jpg', description: 'El reposicionamiento malar, o puntos de anclaje, es una técnica avanzada para restaurar el soporte natural del rostro, mejorar el contorno facial y lograr un efecto de lifting sutil y natural, sin cirugía.' },
    { id: 4, name: 'Relleno de Surcos Nasogenianos', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/mT2BbHVP/Relleno-de-surcos.png', description: 'Nuestro tratamiento de relleno de surcos está diseñado para restaurar el volumen perdido y suavizar esas líneas, devolviendo a tu rostro un aspecto más juvenil y fresco.' },
    { id: 5, name: 'Hilos Tensores PDO', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/ysPRWNCh/Hilos-Tensores-PDO.png', description: 'Los hilos tensores PDO (polidioxanona) son hilos biodegradables que se insertan en la piel para proporcionar soporte estructural y estimular la producción de colágeno, ofreciendo un efecto lifting inmediato.' },
    { id: 6, name: 'Rinomodelación', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/k719DghW/Rinomodelacion.jpg', description: 'La rinomodelación con ácido hialurúnico es un procedimiento no quirúrgico que te permite mejorar la forma y el contorno de tu nariz de manera segura y efectiva, sin necesidad de cirugía.' },
    { id: 7, name: 'Marcación Mandibular y Proyección Mentón', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/HWDTHvvR/Marcacion-mandibular.jpg', description: 'Procedimientos de armonización facial diseñados para definir, equilibrar y fortalecer el contorno del rostro, aportando estructura, simetría y una apariencia más armónica y rejuvenecida.' },
    { id: 8, name: 'Toxina Botulínica', category: ServiceCategory.ArmonizacionFacial, imageUrl: 'https://i.postimg.cc/KGLy9rc5/Toxina-Botulinica.png', description: 'La toxina botulínica, comúnmente conocida como Botox, es uno de los tratamientos estéticos más populares para combatir las arrugas y líneas de expresión relajando temporalmente los másculos faciales.' },
    
    // Rejuvenecimiento
    { id: 9, name: 'Morpheus8', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/h4WKgZ3c/morpheus.jpg', description: 'Tecnología avanzada que combina radiofrecuencia fraccionada con microneedling para tratar arrugas, flacidez, cicatrices y textura desigual, logrando un rejuvenecimiento completo.' },
    { id: 10, name: 'Thermage FLX', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/4JYGcRDK/THERMAGE.jpg', description: 'Tratamiento innovador que utiliza tecnología de radiofrecuencia para abordar de manera efectiva la grasa localizada y mejorar la apariencia de la celulitis.' },
    { id: 11, name: 'Láser CO2 Fraccionado', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/RMYMpZ73/LASER-CO2.png', description: 'Solución eficaz y avanzada para reducir cicatrices y manchas en la piel, transformando la textura y mejorando la apariencia de manera significativa.' },
    { id: 12, name: 'Endolifting', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/qpv3Kdpb/Endolifting-Facial.png', description: 'Tratamiento avanzado de rejuvenecimiento facial no quirúrgico que utiliza energía láser para reafirmar la piel, redefinir contornos y estimular la producción de colágeno.' },
    { id: 13, name: 'Carbón Laser Peel', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/s3VDv8fX/carbon-peel.jpg', description: 'Un revolucionario tratamiento láser no invasivo que ayuda a rejuvenecer la apariencia de la piel envejecida y dañada. Es ideal para tratar imperfecciones menores de la piel, mejorar el tono y la textura.' },
    { id: 14, name: 'HIFU Facial', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/MWH6YQQZ/HIUF.jpg', description: 'HIFU (Ultrasonido Focalizado de Alta Intensidad) es un tratamiento revolucionario para el rejuvenecimiento facial y corporal que ofrece resultados de lifting sin necesidad de cirugía.' },
    { id: 15, name: 'Bioestimuladores de Colágeno', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/D7wXGK7N/Bioestimuladores.jpg', description: 'Sustancias biocompatibles que se inyectan en la piel para estimular la producción natural de colágeno y elastina, mejorando la textura y la firmeza a largo plazo.' },
    { id: 16, name: 'Mesoterapia NCTF', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/2YPk438z/NCTF.jpg', description: 'Tratamiento diseñado para revitalizar la piel desde el interior, utilizando un complejo exclusivo de ácido hialurúnico y más de 50 ingredientes activos.' },
    { id: 17, name: 'Plasma Rico en Plaquetas', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/R4mvD8HH/PLASMA.jpg', description: 'Tratamiento estético innovador que utiliza las propiedades regenerativas de la sangre del propio paciente para mejorar la apariencia de la piel y promover la regeneración celular.' },
    { id: 18, name: 'Profhilo', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/Z4cN0qz3/Profhilo.png', description: 'Tratamiento revolucionario basado en ácido hialurúnico diseñado para mejorar la hidratación, elasticidad y firmeza de la piel, mejorando globalmente la calidad de la piel.' },
    { id: 19, name: 'Factores de Crecimiento', category: ServiceCategory.Rejuvenecimiento, imageUrl: 'https://i.postimg.cc/gY7Yt2V6/Factores-de-crecimiento.jpg', description: 'Una de las terapias más avanzadas en medicina regenerativa estética, diseñadas para estimular la regeneración celular y promover un rejuvenecimiento profundo desde el interior.' },

    // Estética Corporal
    { id: 20, name: 'Morpheus8 Corporal', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/dFzs8DQ4/Morpheus8-corporal.jpg', description: 'Combina microagujas con radiofrecuencia para abordar la grasa localizada y la celulitis, estimulando la producción de colágeno para una piel más firme y tonificada.' },
    { id: 21, name: 'Mesoterapia Corporal', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/gz6GCb49/mesoterapia-grasa.jpg', description: 'Tratamiento altamente efectivo para la reducción de grasa localizada y medidas, ayudándote a esculpir tu figura de manera segura y no invasiva.' },
    { id: 22, name: 'Tratamiento de Estrías', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/LmN4fThz/Eliminacion-de-estrias.jpg', description: 'Ofrecemos soluciones avanzadas para reducir la visibilidad de las estrías, mejorando el aspecto general de la piel mediante técnicas como microagujas y láser.' },
    { id: 23, name: 'Tratamiento de Manchas', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/wx89H44b/Mesoterapia-manchas.jpg', description: 'Utilizamos peelings y mesoterapia para tratar manchas solares, melasma y otras irregularidades pigmentarias, logrando una piel más uniforme y radiante.' },
    { id: 24, name: 'Blanqueamientos', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/9cWFrSXW/blanqueamiento-quimico.jpg', description: 'Tratamientos estéticos diseñados para aclarar la piel y reducir manchas, hiperpigmentación y otros tonos desiguales, promoviendo una renovación celular.' },
    { id: 25, name: 'Enzimas Recombinantes', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/Td3dB01S/IMG-7027.jpg', description: 'Avance innovador en la estética no invasiva para tratar problemas como la celulitis, la flacidez y las acumulaciones localizadas de grasa.' },
    { id: 26, name: 'Endolaser Corporal', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/nnhDmtnw/Endolaser-Corporal.png', description: 'Tratamiento avanzado de moldeado corporal no quirúrgico que utiliza energía láser para reducir grasa localizada, mejorar la flacidez y estimular la producción de colágeno.' },
    { id: 27, name: 'Cavitación', category: ServiceCategory.EstéticaCorporal, imageUrl: 'https://i.postimg.cc/9cJXTpzz/Enzimas-en-papada-(1).jpg', description: 'Tratamiento estético no invasivo que utiliza tecnología de ultrasonido para eliminar la grasa localizada, combatir la celulitis y mejorar la flacidez de la piel.' },
   
    // Nutrición Clínica
    { id: 28, name: 'Consulta Nutricional', category: ServiceCategory.NutricionClinica, imageUrl: 'https://i.postimg.cc/JRP7JqtD/consulta-nutricional.png', description: 'Contamos con un equipo especializado en Nutriología Clínica que trabaja contigo para alcanzar tus metas de salud y belleza de manera sostenible y personalizada.' },
    { id: 29, name: 'Programa Pérdida de Peso', category: ServiceCategory.NutricionClinica, imageUrl: 'https://i.postimg.cc/tyWXDyYZ/perdida-de-peso.jpg', description: 'Nuestro Programa de Inhibición de Apetito combina herramientas científicas y apoyo constante para garantizar resultados efectivos y sostenibles en el control de tu apetito.' },
    
    // Ginecoestetica
    { id: 30, name: 'Labioplastia Láser', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/9W0mB7q6/labioplastia.png', description: 'Procedimiento estético diseñado para remodelar los labios vaginales, ya sea para reducir su tamaño o mejorar su forma, con una intervención precisa y mínimamente invasiva.' },
    { id: 31, name: 'Perineoplastia Láser', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/HHXp3HVT/perineoplastia.jpg', description: 'Procedimiento estético y reconstructivo que utiliza tecnología láser para rejuvenecer y restaurar la elasticidad del perineo.' },
    { id: 32, name: 'Relleno de Labios Mayores', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/PdrTtwKx/relleno-labios-mayores.jpg', description: 'Procedimiento estético que busca aumentar el volumen y mejorar la forma de los labios vaginales externos con ácido hialurúnico.' },
    { id: 33, name: 'Aumento de Punto G', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/hc8t4gB3/Aumento-punto-g.png', description: 'Procedimiento estético que utiliza ácido hialurúnico para aumentar y realzar la sensibilidad del punto G, mejorando la experiencia sexual.' },
    { id: 34, name: 'Tensado Vaginal Láser CO2', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/t9Sy74mV/TENSADO-LASER-CO2.jpg', description: 'Procedimiento no invasivo que utiliza tecnología láser para estimular la regeneración de los tejidos vaginales, mejorando la elasticidad y firmeza.' },
    { id: 35, name: 'Tensado Vaginal HIFU', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/ZJK4Tdj6/Tensado-HIFU.jpg', description: 'Tratamiento no invasivo que utiliza ultrasonido focalizado para estimular la producción de colágeno y elastina en la zona vaginal.' },
    { id: 36, name: 'Vaporización Cervical', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/rc1kxJPS/vaporizacion-cervical.jpg', description: 'Procedimiento médico que utiliza tecnología láser para tratar diversas condiciones del cuello uterino, como lesiones precoces o tejido anormal.' },
    { id: 37, name: 'Chip de la Juventud', category: ServiceCategory.Ginecoestetica, imageUrl: 'https://i.postimg.cc/DFL25Fmt/Pellets.jpg', description: 'Pellets de testosterona que se implantan bajo la piel para liberar lentamente la hormona, restaurando los niveles hormonales y mejorando la salud y el bienestar general.' },

    // Medicina Capilar
    { id: 38, name: 'Mesoterapia Capilar', category: ServiceCategory.MedicinaCapilar, imageUrl: 'https://i.postimg.cc/1mNyk1BL/mesoterapia-capilar.jpg', description: 'Tratamiento médico no invasivo diseñado para combatir la caída del cabello y mejorar su calidad, mediante microinyecciones de un cóctel de vitaminas y nutrientes.' },
    { id: 39, name: 'Alta Frecuencia Capilar', category: ServiceCategory.MedicinaCapilar, imageUrl: 'https://i.postimg.cc/npfLtr6z/alta-frecuencia-capialr.jpg', description: 'Técnica no invasiva que utiliza corrientes eléctricas suaves para estimular el cuero cabelludo, mejorando la circulación sanguínea y oxigenando los folículos pilosos.' },

    // Microcirugías
    { id: 40, name: 'Lipopapada', category: ServiceCategory.Microcirugias, imageUrl: 'https://i.postimg.cc/KxSXMQbn/IMG-4436.jpg', description: 'Procedimiento ambulatorio que consiste en la eliminación de grasa localizada en la zona del cuello y debajo del mentón, redefiniendo el contorno mandibular.' },
    { id: 41, name: 'Alectomía', category: ServiceCategory.Microcirugias, imageUrl: 'https://i.postimg.cc/9WJVP9bz/IMG-6274.avif', description: 'Técnica quirúrgica mínimamente invasiva ideal para quienes desean reducir el ancho de las fosas nasales y mejorar la apariencia de su nariz de manera sutil pero efectiva.' },
    { id: 42, name: 'Lobuloplastia', category: ServiceCategory.Microcirugias, imageUrl: 'https://i.postimg.cc/6WGBkxch/lobuloplastia.jpg', description: 'Procedimiento quirúrgico mínimamente invasivo diseñado para reparar y restaurar el lóbulo de la oreja, ya sea por rasgaduras, dilataciones o deformidades.' },
    { id: 43, name: 'Blefaroplastia', category: ServiceCategory.Microcirugias, imageUrl: 'https://i.postimg.cc/qpkMzYBJ/blefaroplastia.jpg', description: 'Cirugía ambulatoria que mejora la apariencia de los párpados superiores e inferiores, eliminando flacidez, bolsas de grasa y exceso de piel.' },

    // Cosmiatría
    { id: 44, name: 'Depilación Láser Diodo', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/rVtqB2j5/Laser-diodo.jpg', description: 'Método avanzado y efectivo para la eliminación permanente del vello no deseado. Utiliza un láser de diodo que daña el folículo y reduce su capacidad de producir vello.' },
    { id: 45, name: 'Depilación Láser Soprano', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/rVtqB2j5/Laser-diodo.jpg', description: 'Tecnología líder en el mercado reconocida por su eficacia, seguridad y comodidad. Diseñado para adaptarse a todos los tipos de piel, incluyendo pieles bronceadas.' },
    { id: 46, name: 'Facial Profundo', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/PX8dgnyS/Limpieza-profunda.png', description: 'Tratamiento esencial para eliminar las impurezas acumuladas en la piel, dejando el rostro fresco, limpio y renovado, mejorando la oxigenación y la salud general de la piel.' },
    { id: 47, name: 'Casmara', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/xjD9YppB/monodosis-casmara.jpg', description: 'Tratamientos faciales profesionales de alta concentración, diseñados para ofrecer resultados visibles desde la primera aplicación con activos específicos para cada necesidad de la piel.' },
    { id: 48, name: 'Hydrafacial', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/gGNcRDrQ/hydrafacial.jpg', description: 'Innovador tratamiento facial no invasivo que combina limpieza profunda, exfoliación, extracción de impurezas e hidratación intensiva en un solo procedimiento.' },
    { id: 49, name: 'Peeling', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/RmjScqVC/Peeling.jpg', description: 'Procedimiento estético que implica la aplicación de una solución química sobre la piel para exfoliar las capas superficiales, promoviendo la renovación celular.' },
    { id: 50, name: 'Babor', category: ServiceCategory.Cosmiatria, imageUrl: 'https://i.postimg.cc/0PGy5xvq/Babor-jpg.jpg', description: 'Tratamiento de lujo que combina la ciencia avanzada del cuidado de la piel con ingredientes exclusivos para ofrecer resultados excepcionales de hidratación y luminosidad.' },
    
    // Sueroterapia
    { id: 51, name: 'Sueroterapia Complex', category: ServiceCategory.Sueroterapia, imageUrl: 'https://i.postimg.cc/09ywSq9X/Sueroterapia-Complex.png', description: 'Tratamiento intravenoso diseñado para revitalizar el organismo desde el interior, aportando una combinación de glutatión, vitamina C, B12, B6, biotina y antioxidantes.' },
    { id: 52, name: 'Sueroterapia NAD+', category: ServiceCategory.Sueroterapia, imageUrl: 'https://i.postimg.cc/SmxM9pmv/Sueroterapia-NAD.png', description: 'Tratamiento intravenoso avanzado enfocado en la regeneración celular y el bienestar integral, ideal para apoyar los procesos de antiaging, energía y salud metabólica.' },
];


export const TECHNOLOGIES_DATA: Technology[] = [
    { id: 1, name: 'Bioestimuladores', imageUrl: 'https://i.postimg.cc/D7wXGK7N/Bioestimuladores.jpg' },
    { id: 2, name: 'Endolaser Corporal', imageUrl: 'https://i.postimg.cc/nnhDmtnw/Endolaser-Corporal.png' },
    { id: 3, name: 'Endolifting Facial', imageUrl: 'https://i.postimg.cc/qpv3Kdpb/Endolifting-Facial.png' },
    { id: 4, name: 'Hilos Tensores PDO', imageUrl: 'https://i.postimg.cc/ysPRWNCh/Hilos-Tensores-PDO.png' },
    { id: 5, name: 'L?ser Picosecond', imageUrl: 'https://i.postimg.cc/wgVN3BYL/Laser-Picosecond.png' },
    { id: 6, name: 'Profhilo', imageUrl: 'https://i.postimg.cc/Z4cN0qz3/Profhilo.png' },
    { id: 7, name: 'Sueroterapia Complex', imageUrl: 'https://i.postimg.cc/09ywSq9X/Sueroterapia-Complex.png' },
    { id: 8, name: 'Sueroterapia NAD+', imageUrl: 'https://i.postimg.cc/SmxM9pmv/Sueroterapia-NAD.png' },
];

export const TEAM_DATA: TeamMember[] = [
    { id: 1, name: 'Dr. Steele Francisco Mejía López', shortSpecialty: 'Director Médico', specialty: 'Director Médico | Medicina Estética, Armonización Facial, Cirugía de Trasplante Capilar y Endolaser', imageUrl: 'https://i.postimg.cc/R4PZymzZ/Dr-Steele-Mejia.jpg', bio: 'Con más de 10 años de experiencia en el campo de la salud. Graduado en Medicina por la Universidad Autónoma de Santo Domingo, ha complementado su formación con una Maestría en Medicina Estética y un entrenamiento avanzado en trasplante capilar. Actualmente, es Director Médico de Be Aesthetic, donde supervisa y coordina todos los procedimientos médicos, garantizando atención personalizada y de alta calidad para cada paciente. Su enfoque est? en proporcionar soluciones estéticas seguras, innovadoras y adaptadas a las necesidades individuales de sus pacientes. "Creo firmemente en la medicina estética como una forma de realzar la belleza natural, siempre priorizando la salud y el bienestar de mis pacientes. Cada tratamiento es una oportunidad para mejorar la calidad de vida, con resultados que reflejan equilibrio, naturalidad y armon?a."' },
    { id: 2, name: 'Dra. Rosaina De Los Santos Jiménez', shortSpecialty: 'Ginecología Estética', specialty: 'Líder en Ginecología, Obstetricia, Colposcopia y Ginecología Estética', imageUrl: 'https://i.postimg.cc/4XmxT0Jw/Dra-Rosaina-de-los-Santos.jpg', bio: 'Especialista en ginecología-obstetricia, colposcop?a y ginecología estética. Con una amplia experiencia en procedimientos ginecol?gicos avanzados, incluyendo más de 500 partos vaginales, mil cesáreas y 800 colposcopias, se ha consolidado como una figura destacada en su campo. Graduada con honores Cum Laude en 2012 de la UASD. "Mi misión es ofrecer servicios médicos que no solo promuevan la salud femenina, sino que también integren el bienestar estético y el autocuidado, para que cada paciente se sienta cuidada en todas las etapas de su vida."' },
    { id: 5, name: 'Dra. Nathalia Cruz Vásquez', shortSpecialty: 'Medico Estético', specialty: 'Medico Estético | Antiaging y Armonización Facial y Corporal', imageUrl: 'https://i.postimg.cc/jsn2yFmq/Dra-Nathalia-Cruz.jpg', bio: 'Médico con máster en Medicina Estética, Anti-Aging y Nutrici?n, especializada en tratamientos faciales y corporales orientados al rejuvenecimiento integral. Su enfoque combina ciencia, técnica y estética para lograr resultados naturales, seguros y personalizados, priorizando la armon?a facial, la salud de la piel y el bienestar general del paciente. "El antiaging es cuidar hoy lo que deseas conservar ma?ana."' },
    { id: 16, name: 'Dra. Ana Cordero Ramón', shortSpecialty: 'Nutrióloga Clínica y Medicina Estética', specialty: 'Doctora en Medicina | Nutrióloga Clínica | Medicina Estética', imageUrl: anaCorderoImage, bio: 'Doctora en Medicina egresada de la Universidad Autónoma de Santo Domingo (UASD), con Especialidad en Nutriología Clínica del Instituto Tecnol?gico de Santo Domingo (INTEC). Complementa su formación con diplomados en Diabetolog?a y Obesolog?a del Instituto de Capacitaci?n Profesional y Empresarial (INCAPRE/UAPA), así como un Diplomado en Nutrici?n Orientada al Deporte del C?rculo de Inter?s en la Formaci?n Médico-Cient?fica (CIFMEC). Cuenta además con especialidad en Medicina Estética, integrando un enfoque clúnico, preventivo y estético orientado al bienestar integral del paciente. "La salud se construye con conocimiento, prevención y un enfoque integral del bienestar."' },
    { id: 10, name: 'Dra. Sarah Priscila Escaño Estrella', shortSpecialty: 'Anestesióloga y Médico Estético', specialty: 'Anestesióloga y Médico Estético', imageUrl: 'https://i.postimg.cc/33dxHqKR/Dra-Sarah-Escano.jpg', bio: 'Con más de ocho años de experiencia. Graduada en Medicina por la Universidad Autónoma de Santo Domingo, ha realizado una especialización en Anestesiolog?a y un Máster en Medicina Estética y Armonización Facial en Sao Paulo, Brasil. Su pasión por la estética se refleja en su formación continua y experiencia en tratamientos avanzados. "Mi objetivo es que cada paciente logre sentirse más seguro y pleno con su apariencia, brindando resultados naturales y personalizados."' },
    { id: 9, name: 'Dra. Perla M. Simón Villegas', shortSpecialty: 'Medicina y Cosmiatra Avanzada', specialty: 'Doctora en Medicina y Cosmiatra Avanzada', imageUrl: 'https://i.postimg.cc/cxqHhcG8/Dra-Perla-Simon.jpg', bio: 'Profesional comprometida con la salud y el bienestar de sus pacientes. Egresada en Medicina por la Universidad Tecnol?gica de Santiago (UTESA), complementa su formación con un Diplomado en Cosmiatría Avanzada por la UAPA y un Diplomado en Destreza Hospitalarias por CIFMEC en Santo Domingo. Su enfoque en brindar atención médica de calidad la distingue como una profesional empética y dedicada. "Cada paciente es único, y mi misión es ofrecer un cuidado personalizado, comprometido con su salud y belleza."' },
    { id: 4, name: 'Dra. Jismel Ramírez', shortSpecialty: 'Ginecología Estética y Oncológica', specialty: 'Ginecología Estética y Oncológica | Colposcopia', imageUrl: 'https://i.postimg.cc/3K0N2c6c/Dra-Jismel-Ramirez.jpg', bio: 'Médico especialista en ginecología y obstetricia, con subespecialidad en ginecología oncológica y amplia formación quirúrgica. Combina su experiencia clínica con un enfoque en ginecología estética, funcional y antiaging, orientado a la prevención, el bienestar íntimo y la salud integral de la mujer. Su pr?ctica se basa en la medicina humanizada y en soluciones personalizadas. "Cuidar la salud femenina también es preservar su bienestar, autoestima y calidad de vida."' },
    { id: 11, name: 'Dra. Anny Frías', shortSpecialty: 'Cirujana Plástica', specialty: 'Cirujana Plástica, reconstructiva y estética.', imageUrl: 'https://i.postimg.cc/YtsjGHXg/Dra-Anny-Frias.jpg', bio: 'Médico General, Cirujana General y Cirujana Plástica y Reconstructiva, con una trayectoria de casi dos d?cadas dedicada al cuidado integral del paciente. Posee amplia experiencia en procedimientos quirúrgicos y estéticos, integrando precisi?n médica, criterio clúnico y sentido estético. Es miembro activo de SODOCIPRE. "La cirugía y la medicina estética deben practicarse con responsabilidad, ética y un profundo respeto por la salud y la individualidad de cada paciente."' },
    { id: 7, name: 'Dra. Jhanna María Soto Ruiz', shortSpecialty: 'Cirugía Estética y Antiaging', specialty: 'Médico | Cirugía Estética, Reconstructiva y Antiaging', imageUrl: 'https://i.postimg.cc/F9kz0Bq6/Dra-Jhanna-Soto.jpg', bio: 'Médico con formación en cirugía general y cirugía pl?stica reconstructiva, con amplia experiencia acad?mica y quirúrgica. Integra técnicas quirúrgicas y no invasivas con un enfoque estético y antiaging, orientado a la armonización corporal, el rejuvenecimiento y la mejora funcional y estética, siempre con altos est?ndares médicos y cient?ficos. "La estética bien realizada transforma sin perder la esencia de cada persona."' },
    { id: 6, name: 'Dra. Katherin Reyes', shortSpecialty: 'Estética Integral y Bienestar', specialty: 'Doctora en Medicina | Estética Integral y Bienestar', imageUrl: 'https://i.postimg.cc/x0N8L4hY/Dra-Katherine-Reyes.jpg', bio: 'Doctora en Medicina con experiencia clínica en urgencias y consulta general, enfocada en medicina estética y bienestar integral. Aplica un enfoque preventivo y antiaging, orientado a mejorar la calidad de la piel, la salud corporal y la confianza del paciente, siempre desde una base médica responsable y personalizada. "La estética responsable nace del cuidado médico y el respeto por la naturalidad."' },
    { id: 3, name: 'Dra. Anyi María Abreu Tavárez', shortSpecialty: 'Salud Femenina y Estética', specialty: 'Médico | Enfoque en Salud Femenina, Estética y Antiaging', imageUrl: 'https://i.postimg.cc/TTwp3wc3/Dra-Anyi-Abreu.jpg', bio: 'Doctora en Medicina con formación en ginecología y obstetricia, experiencia clínica, auditor?a médica y docencia. Su ejercicio profesional integra la salud femenina con un enfoque preventivo, estético y antiaging, promoviendo el equilibrio hormonal, el bienestar integral y la calidad de vida de la mujer. Se distingue por su ética, compromiso y atención personalizada. "La verdadera estética comienza con la salud, el equilibrio y el cuidado integral de la mujer."' },
    { id: 14, name: 'Dra. Dalva Rosmilda Hernández Canela', shortSpecialty: 'Dermatología y Tricología', specialty: 'Dermatología ? Medicina Interna ? Tricología', imageUrl: 'https://i.postimg.cc/bqBdDh69/Dra-Dalva-Hernandez.jpg', bio: 'Médica especialista en Dermatología y Venereolog?a, con formación en Medicina Interna y enfoque integral en el cuidado de la piel y la salud dermatol?gica. Es Doctora en Medicina Cum Laude por la UASD y actualmente cursa una Subespecialidad en Cirugía Dermatol?gica. "Mi compromiso es ofrecer una dermatolog?a basada en la ciencia, con un enfoque humano, ?tico y personalizado para cada paciente."' },
    { id: 15, name: 'Dra. Haydely Mena', shortSpecialty: 'Medicina Estética', specialty: 'Medicina Estética ? Armonización facial', imageUrl: 'https://i.postimg.cc/5xQy8RGp/Dra-Haydely-Mena.jpg', bio: 'Médica con formación especializada en Medicina Estética, enfocada en el bienestar integral, la armonización facial y el uso de tratamientos innovadores y m?nimamente invasivos. Es Doctora en Medicina por la PUCMM y cuenta con un Máster en Medicina Estética y Longevidad por la Universidad de Alcal? de Henares. "Mi objetivo es realzar la belleza natural de cada paciente, priorizando la seguridad, la ética médica y resultados que armonicen con su esencia."' },
    { id: 18, name: 'Dra. Manuela Pichardo Espinal', shortSpecialty: 'Médico Estético', specialty: 'Médico Estético', imageUrl: manuelaPichardoImage, bio: 'La Dra. Manuela Pichardo Espinal es Médico Estético con formación internacional y experiencia en procedimientos mínimamente invasivos enfocados en el rejuvenecimiento facial, la armonización y el cuidado integral de la piel. Obtuvo su título de Doctor en Medicina en la Universidad Tecnológica de Santiago (UTESA) y cuenta con un Máster en Medicina Estética por el Centro Europeo de Masters y Postgrados (CEMP) / UCAM. Además, posee especialización en Medicina Estética en la Escuela AVICENA (Buenos Aires, Argentina) y formación avanzada en Cosmiatría y Dermatocosmiatría Internacional. "Cada tratamiento debe ser tan único como el paciente que lo recibe."' },
    { id: 13, name: 'Dra. Nixaury María Rodríguez Cuevas', shortSpecialty: 'Médico General', specialty: 'Médico General - Cosmiatría Avanzada', imageUrl: 'https://i.postimg.cc/y1qdjTCV/Dra-Niaury-Rodriguez.jpg', bio: 'Médico General, egresada de la Universidad Tecnol?gica de Santiago (UTESA), con experiencia en atención primaria, medicina interna y manejo integral del paciente. Su perfil se caracteriza por la vocaci?n de servicio, el compromiso con el aprendizaje continuo y el inter?s en el área estética y cosmética. "La medicina debe ejercerse con empat?a, responsabilidad y un verdadero compromiso con el bienestar del paciente."' },
    { id: 12, name: 'Dra. Denisse Marielys Cataño Martínez', shortSpecialty: 'Nutrióloga Clínica', specialty: 'Doctora en Medicina ? Nutrióloga Clínica', imageUrl: 'https://i.postimg.cc/09BrMstf/Dra-Denisse-Catano.jpg', bio: 'Doctora en Medicina, con formación complementaria como Nutrióloga Clínica. Cuenta con experiencia en centros hospitalarios, clínicas privadas e instituciones p?blicas. Su ejercicio profesional se distingue por la dedicaci?n, la disciplina y el enfoque integral en la salud del paciente. "La salud comienza con el cuidado consciente del cuerpo y el compromiso diario con el bienestar."' },
    { id: 8, name: 'Dra. Sorimar Espinal Reyes', shortSpecialty: 'Armonización Orofacial', specialty: 'Estomatolog?a, Armonización Orofacial y Dolor', imageUrl: 'https://i.postimg.cc/mZBrf2Dc/Dra-Sorimar-Espinal.jpg', bio: 'Profesional apasionada por la estomatolog?a y la armonización facial. Graduada en la Pontificia Universidad Cat?lica Madre y Maestra, se ha especializado en el manejo del dolor orofacial y craneomandibular, completando una maestr?a en la Universidad de Salamanca, Espa?a. Con una sólida trayectoria en diversas clínicas y hospitales, la Dra. Espinal est? comprometida con mejorar tanto la salud como la estética facial de sus pacientes. "La armon?a facial y la salud bucal no solo reflejan belleza, sino también bienestar y calidad de vida."' },
    { id: 17, name: 'Dra. Winifer Domínguez', shortSpecialty: 'Armonización Orofacial', specialty: 'Doctora en Odontología | Especialista en Armonización Orofacial', imageUrl: winiferDominguezImage, bio: 'La Dra. Winifer Domínguez es Doctora en Odontología con especialización internacional en Armonización Orofacial, enfocada en realzar la belleza y el equilibrio del rostro mediante procedimientos seguros, personalizados y basados en evidencia científica. Su enfoque se centra en lograr resultados naturales y armónicos, respetando siempre la anatomía facial y la esencia de cada paciente. Cuenta con especialización en Armonización Orofacial en Brasil, formación en Cosmetología en República Dominicana y un Máster en Dermatología Clínica en España, lo que le permite ofrecer un abordaje integral en el rejuvenecimiento facial y el cuidado avanzado de la piel. "La armonización orofacial es el equilibrio perfecto entre ciencia y estética."' },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
    { id: 1, quote: 'Desde que llegu? a Be Aesthetic, me sent? acogida y valorada. El equipo fue incre?blemente profesional y atento, y me explicaron cada paso del tratamiento. Not? cambios en mi confianza desde la primera sesión. ?Totalmente recomendable!', author: 'María L.' },
    { id: 2, quote: 'La atención al cliente en Be Aesthetic es excepcional. Desde la primera consulta, el equipo se tom? el tiempo para entender mis objetivos y preocupaciones. Los resultados superaron mis expectativas, y estoy encantada con la transformación.', author: 'Ana G.' },
    { id: 3, quote: 'Buscaba un lugar que ofreciera un enfoque integral y lo encontr? en Be Aesthetic. La combinaci?n de nutrición y estética me ha ayudado a mejorar no solo mi apariencia, sino también mi salud general. ?Un gran equipo!', author: 'Fernando S.' },
    { id: 4, quote: 'Visitar Be Aesthetic fue una de las mejores decisiones que he tomado. Me ofrecieron tratamientos de vanguardia y me hicieron sentir c?modo en todo momento. El ambiente es relajante y el personal es muy amable. ?Definitivamente volver?!', author: 'Carla M.' },
];

export const LOCATIONS_DATA: Location[] = [
    { id: 'puntacana', name: 'Punta Cana', address: 'Av. Alemania esq. c. Cuba, Los Corales, B?varo.', phone: '+1 (829) 478-3262', mapsLink: 'https://maps.app.goo.gl/jdKc6MvZkUywZzTeA' },
    { id: 'puertoplata', name: 'Puerto Plata', address: 'Direcci?n de Puerto Plata aqu?.', phone: '+1 (809) 268-8948', mapsLink: 'https://maps.app.goo.gl/1cinubz2LksN43Tz6' },
    { id: 'santiago', name: 'Santiago', address: 'Av. Miraflores #30, Los Alamos.', phone: '+1 (829) 285-9105', mapsLink: 'https://maps.app.goo.gl/K24g5JqbwHjka5Jm6' },
    { id: 'santodomingo', name: 'Santo Domingo', address: 'C/ Lic. Carlos Sanchez #15 esq. Av. Tiradentes, Naco.', phone: '+1 (809) 639-2490', mapsLink: 'https://maps.app.goo.gl/hFKAZN8LH4g4Ev6m6' },
];



